<?php

use MoDun\NhanSu\DieuKhien\NhanVienDieuKhien;
use MoDun\NhanSu\DieuKhien\PhongBanDieuKhien;
use MoDun\NhanSu\DieuKhien\ChucVuDieuKhien;
use MoDun\NhanSu\DieuKhien\TongQuanDieuKhien;
use MoDun\NhanSu\DieuKhien\ChamCongDieuKhien;

return [
    'ma' => 'nhan_su',
    'ten' => 'Nhan su',
    'mo_ta' => 'Quan ly nhan vien, phong ban, chuc vu, cham cong va dashboard nhan su.',
    'phien_ban' => '1.0.0',
    'tac_gia' => 'Bee Framework',
    'website' => '',
    'yeu_cau_core' => '1.0.0',
    'yeu_cau_php' => '8.1',
    'kich_hoat_mac_dinh' => false,
    'loai' => 'nghiep_vu',
    'nhom' => 'nghiep_vu',
    'la_mo_dun_loi' => false,
    'phu_thuoc' => ['xac_thuc', 'tai_khoan'],
    'menu' => [
        [
            'ma' => 'nhan_su',
            'tieu_de' => 'Nhan su',
            'bieu_tuong' => 'ti ti-users-group',
            'duong_dan' => '#',
            'quyen' => null,
            'nhom' => 'nghiep_vu',
            'thu_tu' => 40,
            'hien_thi' => true,
            'con' => [
                [
                    'ma' => 'nhan_su_tong_quan',
                    'tieu_de' => 'Tong quan',
                    'bieu_tuong' => 'ti ti-layout-dashboard',
                    'duong_dan' => '/hr/dashboard',
                    'quyen' => 'nhan_su.dashboard',
                    'nhom' => 'nghiep_vu',
                    'thu_tu' => 1,
                    'hien_thi' => true,
                ],
                [
                    'ma' => 'nhan_su_nhan_vien',
                    'tieu_de' => 'Nhan vien',
                    'bieu_tuong' => 'ti ti-user',
                    'duong_dan' => '/nhan-su/nhan-vien',
                    'quyen' => 'nhan_vien.xem',
                    'nhom' => 'nghiep_vu',
                    'thu_tu' => 2,
                    'hien_thi' => true,
                ],
                [
                    'ma' => 'nhan_su_phong_ban',
                    'tieu_de' => 'Phong ban',
                    'bieu_tuong' => 'ti ti-building',
                    'duong_dan' => '/nhan-su/phong-ban',
                    'quyen' => 'phong_ban.xem',
                    'nhom' => 'nghiep_vu',
                    'thu_tu' => 3,
                    'hien_thi' => true,
                ],
                [
                    'ma' => 'nhan_su_chuc_vu',
                    'tieu_de' => 'Chuc vu',
                    'bieu_tuong' => 'ti ti-briefcase',
                    'duong_dan' => '/nhan-su/chuc-vu',
                    'quyen' => 'chuc_vu.xem',
                    'nhom' => 'nghiep_vu',
                    'thu_tu' => 4,
                    'hien_thi' => true,
                ],
                [
                    'ma' => 'nhan_su_cham_cong',
                    'tieu_de' => 'Cham cong',
                    'bieu_tuong' => 'ti ti-calendar-time',
                    'duong_dan' => '/nhan-su/cham-cong',
                    'quyen' => 'cham_cong.xem',
                    'nhom' => 'nghiep_vu',
                    'thu_tu' => 5,
                    'hien_thi' => true,
                ],
            ],
        ],
    ],
    'route' => [
        ['phuong_thuc' => 'GET', 'duong_dan' => '/hr/dashboard', 'yeu_cau_dang_nhap' => true, 'quyen' => 'nhan_su.dashboard', 'xu_ly' => [TongQuanDieuKhien::class, 'index']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nhan-su/tong-quan', 'yeu_cau_dang_nhap' => true, 'quyen' => 'nhan_su.dashboard', 'xu_ly' => [TongQuanDieuKhien::class, 'index']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nhan-su/api/thong-ke', 'yeu_cau_dang_nhap' => true, 'quyen' => 'nhan_su.dashboard', 'xu_ly' => [TongQuanDieuKhien::class, 'apiThongKe']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nhan-su/nhan-vien', 'yeu_cau_dang_nhap' => true, 'quyen' => 'nhan_vien.xem', 'xu_ly' => [NhanVienDieuKhien::class, 'danhSach']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nhan-su/nhan-vien/them', 'yeu_cau_dang_nhap' => true, 'quyen' => 'nhan_vien.them', 'xu_ly' => [NhanVienDieuKhien::class, 'formThem']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nhan-su/nhan-vien/luu', 'yeu_cau_dang_nhap' => true, 'quyen' => 'nhan_vien.them', 'xu_ly' => [NhanVienDieuKhien::class, 'luuMoi']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nhan-su/nhan-vien/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'nhan_vien.xem', 'xu_ly' => [NhanVienDieuKhien::class, 'chiTiet']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nhan-su/nhan-vien/sua/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'nhan_vien.sua', 'xu_ly' => [NhanVienDieuKhien::class, 'formSua']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nhan-su/nhan-vien/cap-nhat/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'nhan_vien.sua', 'xu_ly' => [NhanVienDieuKhien::class, 'luuSua']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nhan-su/nhan-vien/tao-tai-khoan/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'nhan_vien.sua', 'xu_ly' => [NhanVienDieuKhien::class, 'taoTaiKhoanNhanh']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nhan-su/nhan-vien/xoa/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'nhan_vien.xoa', 'xu_ly' => [NhanVienDieuKhien::class, 'xoa']],

        ['phuong_thuc' => 'GET', 'duong_dan' => '/nhan-su/phong-ban', 'yeu_cau_dang_nhap' => true, 'quyen' => 'phong_ban.xem', 'xu_ly' => [PhongBanDieuKhien::class, 'danhSach']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nhan-su/phong-ban/them', 'yeu_cau_dang_nhap' => true, 'quyen' => 'phong_ban.them', 'xu_ly' => [PhongBanDieuKhien::class, 'formThem']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nhan-su/phong-ban/luu', 'yeu_cau_dang_nhap' => true, 'quyen' => 'phong_ban.them', 'xu_ly' => [PhongBanDieuKhien::class, 'luuMoi']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nhan-su/phong-ban/sua/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'phong_ban.sua', 'xu_ly' => [PhongBanDieuKhien::class, 'formSua']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nhan-su/phong-ban/cap-nhat/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'phong_ban.sua', 'xu_ly' => [PhongBanDieuKhien::class, 'luuSua']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nhan-su/phong-ban/xoa/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'phong_ban.xoa', 'xu_ly' => [PhongBanDieuKhien::class, 'xoa']],

        ['phuong_thuc' => 'GET', 'duong_dan' => '/nhan-su/chuc-vu', 'yeu_cau_dang_nhap' => true, 'quyen' => 'chuc_vu.xem', 'xu_ly' => [ChucVuDieuKhien::class, 'danhSach']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nhan-su/chuc-vu/them', 'yeu_cau_dang_nhap' => true, 'quyen' => 'chuc_vu.them', 'xu_ly' => [ChucVuDieuKhien::class, 'formThem']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nhan-su/chuc-vu/luu', 'yeu_cau_dang_nhap' => true, 'quyen' => 'chuc_vu.them', 'xu_ly' => [ChucVuDieuKhien::class, 'luuMoi']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nhan-su/chuc-vu/sua/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'chuc_vu.sua', 'xu_ly' => [ChucVuDieuKhien::class, 'formSua']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nhan-su/chuc-vu/cap-nhat/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'chuc_vu.sua', 'xu_ly' => [ChucVuDieuKhien::class, 'luuSua']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nhan-su/chuc-vu/xoa/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'chuc_vu.xoa', 'xu_ly' => [ChucVuDieuKhien::class, 'xoa']],

        ['phuong_thuc' => 'GET', 'duong_dan' => '/nhan-su/cham-cong', 'yeu_cau_dang_nhap' => true, 'quyen' => 'cham_cong.xem', 'xu_ly' => [ChamCongDieuKhien::class, 'danhSach']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nhan-su/cham-cong/calendar', 'yeu_cau_dang_nhap' => true, 'quyen' => 'cham_cong.xem', 'xu_ly' => [ChamCongDieuKhien::class, 'apiCalendar']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nhan-su/cham-cong/monthly-matrix', 'yeu_cau_dang_nhap' => true, 'quyen' => 'cham_cong.xem', 'xu_ly' => [ChamCongDieuKhien::class, 'apiMonthlyMatrix']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nhan-su/cham-cong/them', 'yeu_cau_dang_nhap' => true, 'quyen' => 'cham_cong.them', 'xu_ly' => [ChamCongDieuKhien::class, 'formThem']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nhan-su/cham-cong/luu', 'yeu_cau_dang_nhap' => true, 'quyen' => 'cham_cong.them', 'xu_ly' => [ChamCongDieuKhien::class, 'luuMoi']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nhan-su/cham-cong/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'cham_cong.xem', 'xu_ly' => [ChamCongDieuKhien::class, 'chiTiet']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nhan-su/cham-cong/sua/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'cham_cong.sua', 'xu_ly' => [ChamCongDieuKhien::class, 'formSua']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nhan-su/cham-cong/cap-nhat/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'cham_cong.sua', 'xu_ly' => [ChamCongDieuKhien::class, 'luuSua']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nhan-su/cham-cong/xoa/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'cham_cong.xoa', 'xu_ly' => [ChamCongDieuKhien::class, 'xoa']],
    ],
    'quyen' => [
        'nhan_su.dashboard',
        'nhan_su.quan_ly',
        'nhan_vien.xem',
        'nhan_vien.them',
        'nhan_vien.sua',
        'nhan_vien.xoa',
        'phong_ban.xem',
        'phong_ban.them',
        'phong_ban.sua',
        'phong_ban.xoa',
        'chuc_vu.xem',
        'chuc_vu.them',
        'chuc_vu.sua',
        'chuc_vu.xoa',
        'cham_cong.xem',
        'cham_cong.them',
        'cham_cong.sua',
        'cham_cong.xoa',
    ],
    'tai_nguyen' => [
        'css' => [
            'mo_dun/nhan_su/css/attendance.css',
        ],
        'js' => [
            'mo_dun/nhan_su/js/apexcharts.min.js',
            'mo_dun/nhan_su/js/components/apex-chart.js',
            'mo_dun/nhan_su/js/dashboard-nhan-su.js',
        ],
    ],
];
