<?php
declare(strict_types=1);

require_once __DIR__ . '/api_nextdns.php';
require_once __DIR__ . '/xu_ly.php';

use MoDun\Nextdns\XuLy;

return [
    'ma' => 'nextdns',
    'ten' => 'NextDNS',
    'mo_ta' => 'Quan ly profile NextDNS, bo loc va danh sach ten mien.',
    'phien_ban' => '2.3.0',
    'tac_gia' => 'Bee Framework',
    'website' => 'https://nextdns.io',
    'yeu_cau_core' => '1.0.0',
    'yeu_cau_php' => '8.1',
    'kich_hoat_mac_dinh' => false,
    'loai' => 'he_thong',
    'nhom' => 'nghiep_vu',
    'la_mo_dun_loi' => false,
    'phu_thuoc' => ['xac_thuc'],
    'menu' => [
        [
            'ma' => 'nextdns',
            'tieu_de' => 'NextDNS',
            'bieu_tuong' => 'ti ti-shield-check',
            'duong_dan' => '#',
            'quyen' => 'xem_nextdns',
            'nhom' => 'nghiep_vu',
            'thu_tu' => 45,
            'hien_thi' => true,
            'con' => [
                [
                    'ma' => 'nextdns_tong_quan',
                    'tieu_de' => 'Tong quan',
                    'bieu_tuong' => 'ti ti-dashboard',
                    'duong_dan' => '/nextdns',
                    'quyen' => 'xem_nextdns',
                    'thu_tu' => 1,
                    'hien_thi' => true,
                    'con' => [],
                ],
                [
                    'ma' => 'nextdns_kiem_tra_ten_mien',
                    'tieu_de' => 'Kiem tra ten mien',
                    'bieu_tuong' => 'ti ti-world-search',
                    'duong_dan' => '/nextdns/kiem-tra-ten-mien',
                    'quyen' => 'kiem_tra_ten_mien_nextdns',
                    'thu_tu' => 2,
                    'hien_thi' => true,
                    'con' => [],
                ],
                [
                    'ma' => 'nextdns_quan_ly_profile',
                    'tieu_de' => 'Quan ly profile',
                    'bieu_tuong' => 'ti ti-user-cog',
                    'duong_dan' => '/nextdns/quan-ly-profile',
                    'quyen' => 'quan_ly_profile_nextdns',
                    'thu_tu' => 3,
                    'hien_thi' => true,
                    'con' => [],
                ],
                [
                    'ma' => 'nextdns_quan_ly_bo_loc',
                    'tieu_de' => 'Quan ly bo loc',
                    'bieu_tuong' => 'ti ti-filter-cog',
                    'duong_dan' => '/nextdns/quan-ly-bo-loc',
                    'quyen' => 'quan_ly_bo_loc_nextdns',
                    'thu_tu' => 4,
                    'hien_thi' => true,
                    'con' => [],
                ],
                [
                    'ma' => 'nextdns_danh_sach_chan_thu_cong',
                    'tieu_de' => 'Danh sach chan',
                    'bieu_tuong' => 'ti ti-shield-x',
                    'duong_dan' => '/nextdns/danh-sach-chan-thu-cong',
                    'quyen' => 'quan_ly_danh_sach_chan_nextdns',
                    'thu_tu' => 5,
                    'hien_thi' => true,
                    'con' => [],
                ],
                [
                    'ma' => 'nextdns_danh_sach_cho_phep_thu_cong',
                    'tieu_de' => 'Danh sach cho phep',
                    'bieu_tuong' => 'ti ti-shield-check',
                    'duong_dan' => '/nextdns/danh-sach-cho-phep-thu-cong',
                    'quyen' => 'quan_ly_danh_sach_cho_phep_nextdns',
                    'thu_tu' => 6,
                    'hien_thi' => true,
                    'con' => [],
                ],
            ],
        ],
    ],
    'route' => [
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nextdns', 'yeu_cau_dang_nhap' => true, 'quyen' => 'xem_nextdns', 'xu_ly' => [XuLy::class, 'tongQuan']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nextdns/cap-nhat-du-lieu', 'yeu_cau_dang_nhap' => true, 'quyen' => 'cap_nhat_du_lieu_nextdns', 'xu_ly' => [XuLy::class, 'capNhatDuLieu']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nextdns/quan-ly-profile', 'yeu_cau_dang_nhap' => true, 'quyen' => 'quan_ly_profile_nextdns', 'xu_ly' => [XuLy::class, 'quanLyProfile']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nextdns/them-profile', 'yeu_cau_dang_nhap' => true, 'quyen' => 'quan_ly_profile_nextdns', 'xu_ly' => [XuLy::class, 'themProfile']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nextdns/cap-nhat-profile/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'quan_ly_profile_nextdns', 'xu_ly' => [XuLy::class, 'capNhatProfile']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nextdns/xoa-profile/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'quan_ly_profile_nextdns', 'xu_ly' => [XuLy::class, 'xoaProfile']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nextdns/quan-ly-bo-loc', 'yeu_cau_dang_nhap' => true, 'quyen' => 'quan_ly_bo_loc_nextdns', 'xu_ly' => [XuLy::class, 'quanLyBoLoc']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nextdns/quan-ly-bo-loc/cap-nhat', 'yeu_cau_dang_nhap' => true, 'quyen' => 'quan_ly_bo_loc_nextdns', 'xu_ly' => [XuLy::class, 'capNhatBoLoc']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nextdns/danh-sach-chan-thu-cong', 'yeu_cau_dang_nhap' => true, 'quyen' => 'quan_ly_danh_sach_chan_nextdns', 'xu_ly' => [XuLy::class, 'danhSachChanThuCong']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nextdns/danh-sach-chan-thu-cong/them', 'yeu_cau_dang_nhap' => true, 'quyen' => 'quan_ly_danh_sach_chan_nextdns', 'xu_ly' => [XuLy::class, 'themDanhSachChan']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nextdns/danh-sach-chan-thu-cong/cap-nhat/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'quan_ly_danh_sach_chan_nextdns', 'xu_ly' => [XuLy::class, 'capNhatDanhSachChan']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nextdns/danh-sach-chan-thu-cong/chuyen-trang-thai/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'quan_ly_danh_sach_chan_nextdns', 'xu_ly' => [XuLy::class, 'chuyenTrangThaiDanhSachChan']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nextdns/danh-sach-chan-thu-cong/xoa/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'quan_ly_danh_sach_chan_nextdns', 'xu_ly' => [XuLy::class, 'xoaDanhSachChan']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nextdns/danh-sach-chan-thu-cong/dong-bo', 'yeu_cau_dang_nhap' => true, 'quyen' => 'quan_ly_danh_sach_chan_nextdns', 'xu_ly' => [XuLy::class, 'dongBoDanhSachChan']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nextdns/danh-sach-cho-phep-thu-cong', 'yeu_cau_dang_nhap' => true, 'quyen' => 'quan_ly_danh_sach_cho_phep_nextdns', 'xu_ly' => [XuLy::class, 'danhSachChoPhepThuCong']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nextdns/danh-sach-cho-phep-thu-cong/them', 'yeu_cau_dang_nhap' => true, 'quyen' => 'quan_ly_danh_sach_cho_phep_nextdns', 'xu_ly' => [XuLy::class, 'themDanhSachChoPhep']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nextdns/danh-sach-cho-phep-thu-cong/cap-nhat/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'quan_ly_danh_sach_cho_phep_nextdns', 'xu_ly' => [XuLy::class, 'capNhatDanhSachChoPhep']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nextdns/danh-sach-cho-phep-thu-cong/chuyen-trang-thai/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'quan_ly_danh_sach_cho_phep_nextdns', 'xu_ly' => [XuLy::class, 'chuyenTrangThaiDanhSachChoPhep']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nextdns/danh-sach-cho-phep-thu-cong/xoa/{id}', 'yeu_cau_dang_nhap' => true, 'quyen' => 'quan_ly_danh_sach_cho_phep_nextdns', 'xu_ly' => [XuLy::class, 'xoaDanhSachChoPhep']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nextdns/danh-sach-cho-phep-thu-cong/dong-bo', 'yeu_cau_dang_nhap' => true, 'quyen' => 'quan_ly_danh_sach_cho_phep_nextdns', 'xu_ly' => [XuLy::class, 'dongBoDanhSachChoPhep']],
        ['phuong_thuc' => 'GET', 'duong_dan' => '/nextdns/kiem-tra-ten-mien', 'yeu_cau_dang_nhap' => true, 'quyen' => 'kiem_tra_ten_mien_nextdns', 'xu_ly' => [XuLy::class, 'kiemTraTenMien']],
        ['phuong_thuc' => 'POST', 'duong_dan' => '/nextdns/kiem-tra-ten-mien', 'yeu_cau_dang_nhap' => true, 'quyen' => 'kiem_tra_ten_mien_nextdns', 'xu_ly' => [XuLy::class, 'xuLyKiemTraTenMien']],
    ],
    'quyen' => [
        'xem_nextdns' => 'Xem tong quan NextDNS',
        'quan_ly_profile_nextdns' => 'Quan ly profile NextDNS',
        'cap_nhat_du_lieu_nextdns' => 'Cap nhat du lieu NextDNS',
        'quan_ly_bo_loc_nextdns' => 'Quan ly bo loc NextDNS',
        'quan_ly_danh_sach_chan_nextdns' => 'Quan ly danh sach chan NextDNS',
        'quan_ly_danh_sach_cho_phep_nextdns' => 'Quan ly danh sach cho phep NextDNS',
        'kiem_tra_ten_mien_nextdns' => 'Kiem tra ten mien NextDNS',
    ],
    'tai_nguyen' => [
        'css' => ['/mo_dun/nextdns/css/nextdns.css'],
        'js' => [],
    ],
];
